In [1]:
import numpy as np
import pandas as pd
import scipy as sp
import scipy.stats

In [6]:
# rank transformation
x1 = np.array([0,1,3,5,10,30,40,50])
x2 = np.array([1,2,3,4,4,3,2,1]) 
x3 = np.array([0,0,0,1,0,3,0,1])

print(sp.stats.rankdata(x1))
print(sp.stats.rankdata(x2))
print(sp.stats.rankdata(x3))

[ 1.  2.  3.  4.  5.  6.  7.  8.]
[ 1.5  3.5  5.5  7.5  7.5  5.5  3.5  1.5]
[ 3.   3.   3.   6.5  3.   8.   3.   6.5]


In [34]:
# log2 transformation
x1 = np.array([0,1,3,5,10,30,40,50])
x2 = np.array([1,2,3,4,4,3,2,1]) 
x3 = np.array([0,0,0,1,0,3,0,1])

x1[x1<2]=2
print(np.log2(x1))

x2[x2<2]=2
print(np.log2(x2))

x3[x3<2]=2
print(np.log2(x3))

[ 2  2  3  5 10 30 40 50]
[ 1.          1.          1.5849625   2.32192809  3.32192809  4.9068906
  5.32192809  5.64385619]
[2 2 3 4 4 3 2 2]
[ 1.         1.         1.5849625  2.         2.         1.5849625  1.         1.       ]
[2 2 3 4 4 3 2 2]
[ 1.         1.         1.         1.         1.         1.5849625  1.         1.       ]


In [33]:
data = np.array([[0,1,3,5,10,30,40,50],
                    [1,2,3,4,4,3,2,1],
                    [0,0,0,1,0,3,0,1]])
data[data < 2] = 2
data = np.log2(data)
data

array([[ 1.        ,  1.        ,  1.5849625 ,  2.32192809,  3.32192809,
         4.9068906 ,  5.32192809,  5.64385619],
       [ 1.        ,  1.        ,  1.5849625 ,  2.        ,  2.        ,
         1.5849625 ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.5849625 ,  1.        ,  1.        ]])

In [10]:
# binary transformation
x1 = np.array([0,1,3,5,10,30,40,50])
x2 = np.array([1,2,3,4,4,3,2,1]) 
x3 = np.array([0,0,0,1,0,3,0,1])

x1[x1!=0]=1
print(x1)

x2[x2!=0]=1
print(x2)

x3[x3!=0]=1
print(x3)

[0 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1]
[0 0 0 1 0 1 0 1]


In [40]:
# normalize transformation
data = np.array([[0,1,3,5,10,30,40,50],
                    [1,2,3,4,4,3,2,1],
                    [0,0,0,1,0,3,0,1]])

data = data / np.sum(data, axis = 0) # column sums
data

array([[ 0.        ,  0.33333333,  0.5       ,  0.5       ,  0.71428571,
         0.83333333,  0.95238095,  0.96153846],
       [ 1.        ,  0.66666667,  0.5       ,  0.4       ,  0.28571429,
         0.08333333,  0.04761905,  0.01923077],
       [ 0.        ,  0.        ,  0.        ,  0.1       ,  0.        ,
         0.08333333,  0.        ,  0.01923077]])