In [1]:
import numpy as np
import pandas as pd
import scipy as sp
import scipy.stats

In [3]:
        labels = np.array([1,1,1,1,0,0,0,0])
        data = np.array([[0,1,3,5,10,30,40,50],
                    [1,2,3,4,4,3,2,1],
                    [0,0,0,1,0,3,0,1]])

In [4]:
mean0 = np.mean(data[:, labels==0], axis = 1)
print(mean0)
mean1 = np.mean(data[:, labels==1], axis = 1)
print(mean1)
tstat = mean1 - mean0
print(tstat)

[ 32.5   2.5   1. ]
[ 2.25  2.5   0.25]
[-30.25   0.    -0.75]


In [5]:
sd0 = np.std(data[:, labels==0], axis = 1, ddof = 1)
sd1 = np.std(data[:, labels==1], axis = 1, ddof = 1)
tstat = (mean1 - mean0)/(sd1 + sd0) 
print(tstat)

[-1.56771435  0.         -0.39180581]


In [ ]:
x1 = np.array([0,1,3,5])
y1 = np.array([10,30,40,50])
x2 = np.array([1,2,3,4])
y2 = np.array([4,3,2,1])
x3 = np.array([0,0,0,1])
y3 = np.array([0,3,0,1])

In [3]:
x = np.array([0,1,3,5,10,30,40,50])
y = np.array([1,2,3,4,4,3,2,1])
z = np.array([0,0,0,1,0,3,0,1])

labels = np.array([1,1,1,1,0,0,0,0])

In [6]:
print(scipy.stats.pearsonr(x,labels)[0])
print(scipy.stats.pearsonr(y,labels)[0])
print(scipy.stats.pearsonr(z,labels)[0])

-0.820287142353
0.0
-0.377964473009


In [7]:
print(scipy.stats.spearmanr(x,labels)[0])
print(scipy.stats.spearmanr(y,labels)[0])
print(scipy.stats.spearmanr(z,labels)[0])

-0.872871560944
0.0
-0.314970394174


## Filtered BH

In [3]:
labels = np.array([1,1,1,1,0,0,0,0])
data = np.array([[0,1,3,5,10,30,40,50],
                    [1,2,3,4,4,3,2,1],
                    [0,0,0,1,0,3,0,1],
                [0,0,0,0,0,10,0,0]])

In [8]:
from scipy.special import comb

data_filter = []
n0 = np.sum(labels==0)
n1 = np.sum(labels==1)
alpha = 0.1

for i in range(np.shape(data)[0]):
    nonzeros = np.count_nonzero(data[i,:])
    if nonzeros < min(n0,n1):
        pval_min = (comb(n0, nonzeros, exact=True) + comb(n1, nonzeros, exact=True))/comb(n0+n1, nonzeros)
        if pval_min < alpha:
            data_filter.append(data[i,:])   
         
    else:
        data_filter.append(data[i,:]) 
        
print(data_filter)

[array([ 0,  1,  3,  5, 10, 30, 40, 50]), array([1, 2, 3, 4, 4, 3, 2, 1])]


In [8]:
np.sum(labels == 0)

4

In [11]:
n0=n1=4
nonzeros=3
pval_min = (comb(n0, nonzeros, exact=True) + comb(n1, nonzeros, exact=True))/comb(n0+n1, nonzeros)
pval_min

0.14285714285714285

In [5]:
min(2,3)

2